const ERROR_VALIDATION = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const OK = 200;
const UNAUTHORIZED = 401;

module.exports = {
  ERROR_VALIDATION,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  OK,
  UNAUTHORIZED,
};
